import mammoth from 'mammoth';

const file = 'C:/Users/visha/Downloads/European Final-20260722T175314Z-1-001/European Final/Spirituality of India Tour for Sudha Jee X01.docx';

async function main() {
  const result = await mammoth.convertToHtml({ path: file });
  let html = result.value;
  
  // Clean up all anchor tags generated by mammoth: <a id="..."></a>
  html = html.replace(/<a\s+id="[^"]+"><\/a>/g, '');
  
  // Split into blocks by block-level tags (paragraphs, headers, list items)
  let blocks = html.split(/<\/?(?:p|h1|h2|h3|h4|h5|h6|ul|li)>/i);
  blocks = blocks.map(b => b.trim()).filter(b => b.length > 0);

  const trip = {
    title: 'Spirituality of India Tour for Sudha Jee X01',
    itinerary: [],
    included: [],
    excluded: []
  };

  let currentSection = 'intro';
  let currentDay = null;

  for (let block of blocks) {
    const textOnly = block.replace(/<[^>]+>/g, '').trim().toLowerCase();
    
    // Check if it's a day header, e.g. "Day 1: Varanasi Sightseeing"
    const dayMatch = block.match(/^(?:<strong>)?Day\s*(\d+)\s*[:-]?\s*(.*?)(?:<\/strong>)?$/i);
    
    if (dayMatch || block.startsWith('Day 0') || block.startsWith('Day 1') || block.startsWith('Day 2') || block.startsWith('Day 3') || block.startsWith('Day 4') || block.startsWith('Day 5')) {
      currentSection = 'itinerary';
      
      let dayNumberMatch = block.match(/Day\s*\d+/i);
      let dayNumber = dayNumberMatch ? dayNumberMatch[0] : 'Day';
      let title = block.replace(/^(?:<strong>)?Day\s*\d+\s*[:-]?\s*/i, '').replace(/<\/strong>$/, '').trim();
      
      // Strip any lingering HTML from title
      title = title.replace(/<[^>]+>/g, '').trim();

      currentDay = {
        day: dayNumber,
        title: title,
        activities: [],
        stay: "Overnight stay"
      };
      trip.itinerary.push(currentDay);
      continue;
    }
    
    if (textOnly.includes('what\'s included') || textOnly.includes('tour cost includes') || textOnly.includes('cost includes')) {
      currentSection = 'included';
      continue;
    }
    if (textOnly.includes('what\'s not included') || textOnly.includes('tour cost excludes') || textOnly.includes('excludes') || textOnly.includes('cost excludes')) {
      currentSection = 'excluded';
      continue;
    }

    if (currentSection === 'itinerary' && currentDay) {
      if (textOnly.includes('overnight stay')) {
        currentDay.stay = block.replace(/<[^>]+>/g, '').trim();
      } else {
        // Keep <strong> tags but remove everything else just to be safe
        let cleanBlock = block.replace(/<\/?(?!strong)[^>]+>/gi, '').trim();
        if (cleanBlock) {
          currentDay.activities.push(cleanBlock);
        }
      }
    } else if (currentSection === 'included') {
      let cleanBlock = block.replace(/<\/?(?!strong)[^>]+>/gi, '').trim();
      if (cleanBlock) trip.included.push(cleanBlock);
    } else if (currentSection === 'excluded') {
      let cleanBlock = block.replace(/<\/?(?!strong)[^>]+>/gi, '').trim();
      if (cleanBlock) trip.excluded.push(cleanBlock);
    }
  }

  console.log(JSON.stringify(trip, null, 2));
}

main();
